name: TestFlight Release (iOS)
on: [push]
jobs:
  internal_release_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Run fastlane setup
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CERTS_REPO_URL: ${{ secrets.CERTS_REPO_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD:  ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_APP_IDENTIFIER: ${{ secrets.FASTLANE_APP_IDENTIFIER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_ID: ${{ secrets.FASTLANE_APPLE_ID }}
          FASTLANE_ITC_TEAM_ID: ${{ secrets.FASTLANE_ITC_TEAM_ID }}
          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}

          ASC_KEY: ${{ secrets.ASC_KEY }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
        run: |
          git config --global url."https://".insteadOf git://
          xcodebuild -version
          yarn install
          git clone "${{ secrets.CERTS_REPO_URL }}" ./certs
          # Pull env variables from certs repo
          # It will inject sentry token in the JS thread
          cp -rf ./certs/.env ./
          cp -rf ./certs/GoogleService-Info.plist ./ios/
          cd ./ios
          pod install
          fastlane build_upload_testflight --verbose

